### ISSUE TITLE
RouterProvider ts issue

### ISSUE THREAD

**Issue by Christopher96u** [SeanCassiere/super-duper-octo-barnacle#3]
Was there a breaking change recently? 
RouterProvider type doesn't match with the signature. Could you have a look?

**Comment by SeanCassiere** [comment]
After updating the dependencies, I just had to suppress a warning in the test setup file, but other than that, everyone looks to be working.

**Comment by chrism1996** [comment]
@SeanCassiere  is that the warning you're talking about?

`Type 'Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, TrailingSlashOption, Record<...>, Record<...>>' is not assignable to type 'Router<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, NonNullable<...>, Record<...>, Record<...>>'.
  The types of '__store.state' are incompatible between these types.
    Type 'RouterState<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, MakeRouteMatch<...>>' is not assignable to type 'RouterState<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, MakeRouteMatch<...>>'.`

That's the only error I got. 
![image](https://github.com/user-attachments/assets/14e5bb50-e97a-483e-9c6c-6b6676110321)

**Comment by SeanCassiere** [comment]
> @SeanCassiere  is that the warning you're talking about?
> 
> `Type 'Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, TrailingSlashOption, Record<...>, Record<...>>' is not assignable to type 'Router<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, NonNullable<...>, Record<...>, Record<...>>'.
>   The types of '__store.state' are incompatible between these types.
>     Type 'RouterState<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, MakeRouteMatch<...>>' is not assignable to type 'RouterState<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, MakeRouteMatch<...>>'.`
> 
> That's the only error I got. 
> ![image](https://github.com/user-attachments/assets/14e5bb50-e97a-483e-9c6c-6b6676110321)
> 

No it was an unused variable warning.

**Comment by chrism1996** [comment]
> > @SeanCassiere  is that the warning you're talking about?
> > `Type 'Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, TrailingSlashOption, Record<...>, Record<...>>' is not assignable to type 'Router<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, NonNullable<...>, Record<...>, Record<...>>'. The types of '__store.state' are incompatible between these types. Type 'RouterState<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, MakeRouteMatch<...>>' is not assignable to type 'RouterState<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, MakeRouteMatch<...>>'.`
> > That's the only error I got.
> > ![image](https://private-user-images.githubusercontent.com/159506618/382129446-14e5bb50-e97a-483e-9c6c-6b6676110321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTMyMjksIm5iZiI6MTczMDQxMjkyOSwicGF0aCI6Ii8xNTk1MDY2MTgvMzgyMTI5NDQ2LTE0ZTViYjUwLWU5N2EtNDgzZS05YzZjLTZiNjY3NjExMDMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQyMjE1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmI2OGNjNzk1ZmM0Y2M4YWIwYjE2NDAxZjExZWM4YmRjOTdlYTM5ZTViNzM4MmE3NjhkODUwZTRkYWQzNDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.chGHPX1tJ7pF86-nJEbPPTZr8MhyO71yguH0Q7y7CsQ)
> 
> No it was an unused variable warning.

Do you mean if I create a code snippet to reproduce the issue? Sorry for the late reply.

**Comment by SeanCassiere** [comment]
> > > @SeanCassiere  is that the warning you're talking about?
> > > `Type 'Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, TrailingSlashOption, Record<...>, Record<...>>' is not assignable to type 'Router<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, NonNullable<...>, Record<...>, Record<...>>'. The types of '__store.state' are incompatible between these types. Type 'RouterState<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, Route<AnyRoute, "/", "/" | `/${any}/`, string, "/" | `/${any}/`, undefined, Record<never, string>, ... 5 more ..., unknown>[], unknown>, MakeRouteMatch<...>>' is not assignable to type 'RouterState<RootRoute<undefined, RouterContext, AnyContext, AnyContext, {}, undefined, RootRouteChildren, FileRouteTypes>, MakeRouteMatch<...>>'.`
> > > That's the only error I got.
> > > ![image](https://private-user-images.githubusercontent.com/159506618/382129446-14e5bb50-e97a-483e-9c6c-6b6676110321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTMyMjksIm5iZiI6MTczMDQxMjkyOSwicGF0aCI6Ii8xNTk1MDY2MTgvMzgyMTI5NDQ2LTE0ZTViYjUwLWU5N2EtNDgzZS05YzZjLTZiNjY3NjExMDMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQyMjE1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmI2OGNjNzk1ZmM0Y2M4YWIwYjE2NDAxZjExZWM4YmRjOTdlYTM5ZTViNzM4MmE3NjhkODUwZTRkYWQzNDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.chGHPX1tJ7pF86-nJEbPPTZr8MhyO71yguH0Q7y7CsQ)
> > 
> > No it was an unused variable warning.
> 
> Do you mean if I create a code snippet to reproduce the issue? Sorry for the late reply.

Sure. 

Either ways, this is just a helper for testing. You can just `any` cast it since it has no bearing on the app's runtime.
